### ISSUE TITLE
broken as of incubator-cordova-ios d8575d7ee, needs screen orientation api updates

### ISSUE THREAD

**Issue by max-mapper** [alunny/ChildBrowser#20]
https://github.com/apache/incubator-cordova-ios/commit/d8575d7eece28ec2c90de4b448af729accaf2567 added new semantics for screen orientation and broke childbrowser

cc @shazron

**Comment by shazron** [comment]
I'm fixing this - don't know how this is synced to phonegap-plugins, i'll fix both and send a pr here

**Comment by shazron** [comment]
Updated ChildBrowser in phonegap-plugins: https://github.com/phonegap/phonegap-plugins/commit/d4ce61db03cd4f9b69f075b8ca148637c04f713c
1. Fixed iOS 6 orientation issue
2. ARC/non-ARC compatibility 
3. Uncrustified

Tested on iOS 5 and iOS 6.

**Comment by max-mapper** [comment]
awesome! thanks shaz

**Comment by regrunge** [comment]
if App in landscape, after closing childbrowser the view resizes wrongly with a black rectangle on the right, like if it was in portrait (ipad3 ios6). found many with this bug, where could be the bug? i'd love to help but i need some directions on the Cordova 2.0 vs. 2.1 orientation issue, it's still not clear to me

**Comment by elijnzaad** [comment]
I'm experiencing the same problem as regrunge reported after applying an update to MainViewController.m. This update corrects the viewport offset for iOS6 as posted by petersjay:
- (void)viewWillAppear:(BOOL)animated
  {
  // Set the main view to utilize the entire application frame space of the device.
  // Change this to suit your view's UI footprint needs in your application.
  self.view.frame = [[UIScreen mainScreen] applicationFrame];
  
  [super viewWillAppear:animated];
  }

Adding this results in the behavior described by regrunge. Removing it results in the top of the view disappearing behind the iOS statusbar, but will leave the orientation correct after returning from ChildBrowser.

**Comment by aklivingston** [comment]
Same problem as regrunge (iPad 3, 5.1.1)

**Comment by regrunge** [comment]
I've reset the self.view.frame in MainViewController.m like this:
- (void)viewWillAppear:(BOOL)animated
  {
  
  // Set the main view to utilize the entire application frame space of the device.
  // Change this to suit your view's UI footprint needs in your application.
  self.view.frame = CGRectMake(0,0,[[UIScreen mainScreen] applicationFrame].size.height,[[UIScreen mainScreen] applicationFrame].size.width);
  
  [super viewWillAppear:animated];
  }

seems to work if landscape only, but please an expert that could test it? maybe with an if statement checking the orientation?

**Comment by regrunge** [comment]
ok i've tried to make the IF statement:
- (void)viewWillAppear:(BOOL)animated
  {
  if(self.interfaceOrientation > 2){
  // Set the main view to utilize the entire application frame space of the device.
  // Change this to suit your view's UI footprint needs in your application.
      self.view.frame = CGRectMake(0,0,[[UIScreen mainScreen] applicationFrame].size.height,[[UIScreen mainScreen] applicationFrame].size.width);
  } else {
      self.view.frame = [[UIScreen mainScreen] applicationFrame];
  }
  [super viewWillAppear:animated];
  }

**Comment by elijnzaad** [comment]
Thanks regrunge, the IF statement works for me!

**Comment by regrunge** [comment]
Cool now I got a similar problem with the barcodescanner ;( ! I read about child views but that little trick doesn't work on the barcode. I f only I knew objective-c....

**Comment by aklivingston** [comment]
Will childbrowser be updated to include this fix?

**Comment by regrunge** [comment]
I have actually "hacked" Cordova not Childbrowser, and I don't know what are they doing for orientation's problems in Cordova (Phonegap).

**Comment by alunny** [comment]
Oh this thing.

Looks like @shazron's patch doesn't apply easily - I'll port the relevant parts into here and close when done.

@shazron: do you know what versions of Cordova the patched version works with?

**Comment by mygithub747** [comment]
I am running into strange issue, when the ChildBrowser closes the main view inherits the ChildBrowser dimensions, so for e.g if the MainView had a long long HTMl page and was able to scroll and after clicking a link to open ChildBrowser and then closing it causes MainView to not scroll as if the mainview dimension gets locked in. Any ideas how to resolve this. I tried some of the fixes mentioned above but doesn't work.
