### ISSUE TITLE
Cordova 2.2.0

### ISSUE THREAD

**Issue by 0x6a68** [alunny/ChildBrowser#24]
Got following compile error

```
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_CDVPlugin", referenced from:
      _OBJC_CLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
  "_OBJC_CLASS_$_CDVPluginResult", referenced from:
      objc-class-ref in ChildBrowserCommand.o
  "_OBJC_CLASS_$_CDVViewController", referenced from:
      _OBJC_CLASS_$_MainViewController in MainViewController.o
  "_OBJC_METACLASS_$_CDVPlugin", referenced from:
      _OBJC_METACLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
  "_OBJC_METACLASS_$_CDVViewController", referenced from:
      _OBJC_METACLASS_$_MainViewController in MainViewController.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by 0x6a68** [comment]
my fault... sorry

**Comment by ChristianWeyer** [comment]
What was your fault? I have the same... ;)

**Comment by 0x6a68** [comment]
it was a linking/referencing problem in xcode. 
Project Navigator -> Your Project -> Build Phases -> Link Binary With Libraries (ensure that libCordova.a is in there)

**Comment by ChristianWeyer** [comment]
Sorted that out as well, thx!

Am 13.11.2012 um 11:19 schrieb "Johannes Troeger" <notifications@github.com<mailto:notifications@github.com>>:

it was a linking/referencing problem in xcode.
Project Navigator -> Your Project -> Build Phases -> Link Binary With Libraries (ensure that libCordova.a is in there)

**Comment by jbatchelor** [comment]
My apologies if this is really n00b, but if libCordova.a is colored red in that list, does that mean the file is missing? If so, where do I find it?

**Comment by alunny** [comment]
If libCordova.a is red, it means it hasn't been built yet. You can choose to build it from the drop-down on the top-right of the Xcode window.

**Comment by ttantawy** [comment]
what if it is already there and i have this same error?

**Comment by qetr1ck-op** [comment]
Actually the same problem;
added libCordova.a in Link Binary With Libraries;
and problem with build still appear...

"_OBJC_CLASS_$_CDVPluginResult", referenced from:
      objc-class-ref in InAppPurchase.o
  "_OBJC_METACLASS_$_CDVPlugin", referenced from:
      _OBJC_METACLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
      _OBJC_METACLASS_$_Downloader in Downloader.o
      _OBJC_METACLASS_$_InAppPurchase in InAppPurchase.o
  "_OBJC_METACLASS_$_CDVViewController", referenced from:
      _OBJC_METACLASS_$_MainViewController in MainViewController.o
  "_OBJC_CLASS_$_CDVPlugin", referenced from:
      _OBJC_CLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
      _OBJC_CLASS_$_Downloader in Downloader.o
      _OBJC_CLASS_$_InAppPurchase in InAppPurchase.o
  "_OBJC_CLASS_$_CDVViewController", referenced from:
      _OBJC_CLASS_$_MainViewController in MainViewController.o
ld: symbol(s) not found for architecture armv7s
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by luohaiquan** [comment]
@qetr1ck-op I have the same problem with you, so what's the solution ,thank you

**Comment by vinaygiri** [comment]
hi 
here also same issue any solutions please

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CDVPluginResult", referenced from:
      objc-class-ref in socialShare.o
  "_OBJC_CLASS_$_ZBarReaderViewController", referenced from:
      objc-class-ref in ChildBrowserCommand.o
  "_OBJC_CLASS_$_CDVViewController", referenced from:
      _OBJC_CLASS_$_MainViewController in MainViewController.o
  "_OBJC_CLASS_$_GAI", referenced from:
      objc-class-ref in GoogleAnalyticsPlugin.o
  "_OBJC_CLASS_$_CDVPlugin", referenced from:
      _OBJC_CLASS_$_GoogleAnalyticsPlugin in GoogleAnalyticsPlugin.o
      _OBJC_CLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
      _OBJC_CLASS_$_socialShare in socialShare.o
  "_ZBarReaderControllerResults", referenced from:
      -[ChildBrowserCommand imagePickerController:didFinishPickingMediaWithInfo:] in ChildBrowserCommand.o
  "_OBJC_METACLASS_$_CDVViewController", referenced from:
      _OBJC_METACLASS_$_MainViewController in MainViewController.o
  "_OBJC_METACLASS_$_CDVPlugin", referenced from:
      _OBJC_METACLASS_$_GoogleAnalyticsPlugin in GoogleAnalyticsPlugin.o
      _OBJC_METACLASS_$_ChildBrowserCommand in ChildBrowserCommand.o
      _OBJC_METACLASS_$_socialShare in socialShare.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
