### ISSUE TITLE
ChildBrowser + PhoneGap Hydra = Missing location bar Images

### ISSUE THREAD

**Issue by dustyjewett** [alunny/ChildBrowser#31]
When you use PhoneGap Build Hydra, the ChildBrowser looks in the assets/www folder for the childbrowser folder and it's images  Hydra, however, downloads the files separately and stores them in a different directory.  When it runs, you just get three small boxes, that are thankfully clickable.

**Comment by alunny** [comment]
Thanks for the report - please forward this on to the phonegap/build repo (I'm no longer an employee of Adobe, so I don't handle anything related to PhoneGap Build).
