### ISSUE TITLE
Request: Hide/Show specific buttons in navigation bar

### ISSUE THREAD

**Issue by KimTLee** [alunny/ChildBrowser#37]
I have a request: could someone add the functionality to show/hide the different buttons in the navigation bar? What I'm currently interested into is to only have the "Done" button shown, I don't need the other buttons and would prefer them to be hidden to avoid user's confusion.

I'm using that plugin throw PhoneGap Build and currently don't know anything about Java or objective C...

**Comment by cemerson** [comment]
Hey there – this may/may not work for you but I maintain a modified version of the InAppBrowser plugin where I have added some custom features – one that might help you here is:  enablearrowbuttons=no

When this parameter (and value) is provided, no arrow buttons show up for iOS or Android.
https://github.com/cemerson/cordova-inappbrowser-ce

I don’t know how PG Build works (stopped looking after BETA) but you can add my plugin via the CLI like this:
$ cordova plugins add https://github.com/cemerson/cordova-inappbrowser-ce.git

Let me know if you try it and/or its helpful!

**Comment by KimTLee** [comment]
Hi, thanks for your answer.

That sounds like exactly what I need.

Do you think your changes could be pushed to this repo? The thing is I don't have any working iOS environment and I use PhoneGap Build to do the build for me.

This repo has been added to the whitelisted plugins of PGB (https://build.phonegap.com/plugins/2), so PGB automatically gets the latest version and puts the iOS and Android parts where needed. Also I've added some hooks in my git repos so that each time I push something the changes are sent to PGB and the new builds are usually available less than a minute afterwards. There is also the Hydration plugin which is integrated in PGB which is really convenient to use during development time.

We could probably have your plugin added also to the whitelisted plugins of PGB, but it might be more convenient to only have one.

Thanks again.

**Comment by alunny** [comment]
Hi all,

For updating PhoneGap Build, please see this fork of the project: https://github.com/phonegap-build/ChildBrowser

I am no longer working on PhoneGap Build, so any documentation pointing to this repo is out of date. I've edited the README to make that clear.

@hardeep and/or @goya can help get any changes merged into that.
